### PR TITLE
[QOLDEV-223] fix height of accordion heading with image

### PR DESCRIPTION
**Pull request by ThrawnCA**
- Use 'inline-block' regardless of image presence

### CODE REVIEW

**Comment by RossWebsterWork** [comment]
I don't think it's directly related to this change, but in the Storybook the blue border on the accordion title seems to be too far on the right side

**Review by RossWebsterWork — APPROVED** [review]

**Comment by ThrawnCA** [comment]
> I don't think it's directly related to this change, but in the Storybook the blue border on the accordion title seems to be too far on the right side

Thanks for the spot. Yeah, I don't think it's caused by this change, but it was better on 4.1.0, so this is something to fix.

**Comment by RossWebsterWork** [comment]
The border is even now, although it's spaced further out than what it was before, is this intended?

**Review by RossWebsterWork — APPROVED** [review]

**Comment by ThrawnCA** [comment]
> The border is even now, although it's spaced further out than what it was before, is this intended?

Compare it to SWE 4.1.0...

**Comment by RossWebsterWork** [comment]
> Compare it to SWE 4.1.0...

Sorry, but how would I actually compare it? Is https://www.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/accordion at SWE 4.1.0, should I be looking at Figma https://www.figma.com/file/WpanghHaeTZgwGOJE2wnKT/Hyperlinks-accessibility-review-project, or is there a way to view it in Chromatic?

**Comment by ThrawnCA** [comment]
> Sorry, but how would I actually compare it?
> ...
> or is there a way to view it in Chromatic?

That's possible, or you can compare locally.

You can view a Chromatic build for branch release-v4.1.0, eg build 345, or you can check out qg-web-template locally and use Node 14 to run 'npm run start'.

**Comment by RossWebsterWork** [comment]
> That's possible, or you can compare locally.
> 
> You can view a Chromatic build for branch release-v4.1.0, eg build 345, or you can check out qg-web-template locally and use Node 14 to run 'npm run start'.

Build 345 didn't run because it was over the monthly limit at the time and there aren't any other recent builds for 4.1.0, and I'm currently on Node 10 and I'm not sure how much hassle it would be to switch to Node 14 just to compare the border styles, but I've still approved the change

**Comment by ThrawnCA** [comment]
Sorry, my bad. Build 260 should work.

**Pull request merged**
