### PR TITLE
QOLDEV-62 make checkbox styling consistent

### PR DESCRIPTION
**Pull request by ThrawnCA**
Compare to designs on Figma: https://www.figma.com/file/5BrkUy62yKzGbRJnrUcLLM/Form-control-inputs%3A-Radio-and-checkbox?node-id=19%3A1893

- Use black checkmark on a white background regardless of browser defaults.
- Apply blue outline on focus.

### CODE REVIEW

**Comment by RossWebsterWork** [comment]
Comparing Chromatic to Figma, the checkboxes seem a little off-centre compared to their labels, the checkbox outline is a little different and the checkmark seems to be rotated, otherwise it looks good.

**Comment by ThrawnCA** [comment]
> Comparing Chromatic to Figma, the checkboxes seem a little off-centre compared to their labels, the checkbox outline is a little different and the checkmark seems to be rotated, otherwise it looks good.

Yeah, I wasn't able to perfectly replicate the Figma design. I figured it's still closer than the status quo.

**Comment by ThrawnCA** [comment]
@RossWebsterWork Okay, I've adjusted the polygon definition, so the check mark should be closer to Figma now.

**Comment by ThrawnCA** [comment]
Chromatic shows the radio button outlines being square, but local testing with both Firefox and Chrome shows them as circular.

**Comment by ThrawnCA** [comment]
Looks like Chromatic is using older browser versions, see https://www.chromatic.com/docs/infrastructure-release-notes

**Review by chris-randall-qol — APPROVED** [review]

**Pull request merged**
