### PR TITLE
Add fail class

### PR DESCRIPTION
**Pull request by matthewharding**
Add in fail class for statuses in the new style.

### CODE REVIEW

**Comment by duttonw** [comment]
Hi @matthewharding,

Could you include a screenshot of how this is meant to look like when implemented. 

We do need to check that it is good for accessibility etc. @jackie-QLD  @andersmx 

regards,

@duttonw

**Comment by matthewharding** [comment]
image

**Comment by andersmx** [comment]
Hey @matthewharding  just curious as to the context in which this is being applied.

As we have warning for failed cases/validation:
warning

In fail validation, this is used to show a sub-list of failed fields. 

Just concerned if we add this in for you as a component, it will be consumed incorrectly (leading to inconsistency).

**Comment by matthewharding** [comment]
@andersmx the context would be a 'non-recoverable' failure. I was working on a payment plan calculator where an outcome was 'it is not possible at all'. This is different to the standard form validation warning which is recoverable.

**Comment by duttonw** [comment]
Hi @matthewharding ,

Please review https://www.seniors-concessions.services.qld.gov.au/eligibility#/ and click no to the first question.

Would this be suitable to your needs?

**Comment by jackie-QLD** [comment]
Hi @matthewharding ,

We're happy to support this variation of our existing [Alert component](https://qld-gov-au.github.io/web-template-release/components.html#alerts) in the context of a critical, 'non-recoverable' failure, and make this available globally.

To ensure this style of Alert is used sparingly though (to maintain its effectiveness across the site), I'd just like to understand your use case a little more in case there is another more appropriate solution. Could you just confirm that in your use case this is a critical error whereby the customer cannot actually complete the process, as opposed to the customer receiving an unfavourable outcome (i.e. ineligibility) based on their form entries?

This variation of Alert does have its place in the previously mentioned context, so we've progressed this to have it designed/developed and added to the SWE3 assets.

Cheers, Jackie

**Comment by asifamingov** [comment]
Hi @matthewharding 

Could you please go through William and Jackie comments above and please let me know if you are happy to close this pull request?

**Pull request closed without merging**
