### PR TITLE
[QOLDEV-250] skip focus/active outlines for links inside buttons

### PR DESCRIPTION
**Pull request by ThrawnCA**
- The button will handle the outline, we don't want to double up

### CODE REVIEW

**Comment by RossWebsterWork** [comment]
The change seems good, but in the story, I noticed that the "Link inside" button's hover state doesn't match hovering over it's default case, where it still has blue text and an underline

**Review by RossWebsterWork — APPROVED** [review]

**Comment by ThrawnCA** [comment]
> The change seems good, but in the story, I noticed that the "Link inside" button's hover state doesn't match hovering over it's default case, where it still has blue text and an underline

Good catch, I messed up the story content (left out most of the 'a' tags). Should be resolved now.

**Comment by RossWebsterWork** [comment]
That's fixed the story links, although looking at it further, the hover effect only triggers when the inner text is hovered, and not the button itself (unlike btn-outline-dark and btn-link), including when the button is disabled.
Also the disabled btn-default visually reacts when clicked, and the btn-link is the only disabled button to not change the mouse to a hand (testing on Edge).

**Comment by ThrawnCA** [comment]
@RossWebsterWork Those seem like existing issues...Worth looking into at some point, but I'm still willing to merge this.

**Pull request merged**
