### PR TITLE
QOLDEV-681 Improving templates structure in storybook

### PR DESCRIPTION
**Pull request by ghazal-salehi**
As requested by our designers, the default Topic Index temple is without an aside and thumbnails.

**Before:**
image

**After:**
image

### CODE REVIEW

**Review by ThrawnCA — CHANGES_REQUESTED** [review]
Tabbed folders have been lost in a context where that doesn't look intentional.

**Comment by ghazal-salehi** [comment]
What do you mean by tabbed folders?

**Comment by ghazal-salehi** [comment]
Okay it seems it is related to https://qld-gov-au.github.io/qg-web-template/?path=/docs/components-search-categories--docs. Some libraries are missing. It is a franchise customised component. I'll check with the team to see if we need to to stay in storybook at all.

**Comment by ghazal-salehi** [comment]
I updated the css url. It should be working now.

**Review by ThrawnCA — APPROVED** [review]

**Pull request merged**
