### PR TITLE
Qol 8600 new create a video embed component on swe

### PR DESCRIPTION
**Pull request by asifamingov**

### CODE REVIEW

**Review by ThrawnCA — APPROVED** [review]

**Review by devonpis — COMMENTED** [review]
better to embed a vimeo example in video.html as well as per ticket requirement

**Review by ThrawnCA — APPROVED** [review]

**Comment by asifamingov** [comment]
> 

That just needs a video URL and that should work with any provider. I am trying to find a video I can put as an example there

> better to embed a vimeo example in video.html as well as per ticket requirement

I think the component will work with any video provider because HTML just needs the video URL, I will both the examples.

**Comment by asifamingov** [comment]
> better to embed a vimeo example in video.html as well as per ticket requirement

The example is generic , the component should work with any video URL. I tried Vimeo and it is working https://qld-gov-au.github.io/qg-web-template/components/video.html

**Comment by devonpis** [comment]
> > better to embed a vimeo example in video.html as well as per ticket requirement
> 
> The example is generic , the component should work with any video URL. I tried Vimeo and it is working https://qld-gov-au.github.io/qg-web-template/components/video.html

it would be nice to include the URLs (eg.https://player.vimeo.com/video/686195960?h=4c9609f09c&badge=0 for vimeo and https://www.youtube.com/embed/NpmB80pWUsk?rel=0 for youtube) in the component description so the user will expect what to pass to the `src` of the iframe. anyway this may be taken care of in Rebacca's doc.

**Review by devonpis — APPROVED** [review]

**Pull request merged**
