### PR TITLE
QOLDEV-268 fix digital dashboard styling errors

### PR DESCRIPTION
**Pull request by ThrawnCA**
- Don't apply standard margins to elements that need to manage their own positioning
- Don't apply new styling to legacy buttons

### CODE REVIEW

**Comment by RossWebsterWork** [comment]
There's a few exclusions for #tabbed-nav, would it be better to let that element override the default with its own styling rather than excluding it from every default?

**Comment by ThrawnCA** [comment]
> There's a few exclusions for #tabbed-nav, would it be better to let that element override the default with its own styling rather than excluding it from every default?

Not really. It's part of the digital dashboard, not part of SWE, so we would then create a mutual dependency and have to release both at the same time. And different uses of tabbed-nav could theoretically have different requirements; all we're doing here is choosing not to impose a uniform rule on them.

**Comment by RossWebsterWork** [comment]
> > There's a few exclusions for #tabbed-nav, would it be better to let that element override the default with its own styling rather than excluding it from every default?
> 
> Not really. It's part of the digital dashboard, not part of SWE, so we would then create a mutual dependency and have to release both at the same time. And different uses of tabbed-nav could theoretically have different requirements; all we're doing here is choosing not to impose a uniform rule on them.

If #tabbed-nav is not part of SWE, then wouldn't it be best practice to not modify SWE to fit every project that uses it? And different uses of #tabbed-nav could have different requirements, and if a project uses it and wants those default stylings, then it would need to re-create them or use a different id. And if adjustments are made to exclude such navigation, would it be better to create a SWE class for it?
I don't think there would be a mutual dependency, as surely the Digital Dashboard could add a styling that specifies this margin is kept at zero before the new SWE stylings are applied? I'm not sure if Digital Dashboard automatically uses the latest version of SWE, or if it is updated manually, giving time for any adjustments if required.
I think this change will still work fine, but I'm just not sure if it's best practice?

**Comment by ThrawnCA** [comment]
> If #tabbed-nav is not part of SWE, then wouldn't it be best practice to not modify SWE to fit every project that uses it?

For now, this is just matching SWE 4.1.0. There are more tasks being created (QOLDEV-272) to bring the Digital Dashboard in line with SWE, and we may be able to find a better solution as part of one of those tasks.

**Review by RossWebsterWork — APPROVED** [review]

**Pull request merged**
