### PR TITLE
QOL-9431 Split text-decoration into individual declarations

### PR DESCRIPTION
**Pull request by ThrawnCA**
Safari on iOS does not fully support the combined 'text-decoration' declaration, so for greater compatibility, it's best to split it into individual declarations, 'text-decoration-line', 'text-decoration-style', etc.

SASS mixins help to keep this DRY.

### CODE REVIEW

**Review by RossWebsterWork — APPROVED** [review]

**Comment by ThrawnCA** [comment]
@RossWebsterWork Are you able to also review the Chromatic changes? As far as I can see, the breadcrumbs basically haven't changed; maybe it thinks they've moved a pixel to the right, or something? And the extra video button appears to be coming from Vimeo, not from us; it's an iframe from their site.

**Comment by RossWebsterWork** [comment]
@ThrawnCA I had a look at the changes on Chromatic and am happy to approve them, but I can't approve it myself.
I've just signed up for a Chromatic account with my work email and have the option to connect the profile to my GitHub account, do you think I should try this?

**Comment by ThrawnCA** [comment]
> I've just signed up for a Chromatic account with my work email and have the option to connect the profile to my GitHub account, do you think I should try this?

The permissions for our repo are managed in GitHub, so I believe so.

**Comment by RossWebsterWork** [comment]
Yep, connecting my GitHub account allowed me to review and accept Chromatic, which I have done now

**Review by duttonw — APPROVED** [review]

**Pull request merged**
